services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - PYTHON_KEYRING_BACKEND=keyrings.cryptfile.cryptfile.CryptFileKeyring
    volumes:
      - .:/app
      - python_keyring:/root/.local/share/python_keyring

volumes:
  python_keyring:
